# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: etcd3/etcdrpc/kv.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'etcd3/etcdrpc/kv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65tcd3/etcdrpc/kv.proto\x12\x10\x65tcd3.etcdrpc.kv\"u\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x17\n\x0f\x63reate_revision\x18\x02 \x01(\x03\x12\x14\n\x0cmod_revision\x18\x03 \x01(\x03\x12\x0f\n\x07version\x18\x04 \x01(\x03\x12\r\n\x05value\x18\x05 \x01(\x0c\x12\r\n\x05lease\x18\x06 \x01(\x03\"\xaf\x01\n\x05\x45vent\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.etcd3.etcdrpc.kv.Event.EventType\x12&\n\x02kv\x18\x02 \x01(\x0b\x32\x1a.etcd3.etcdrpc.kv.KeyValue\x12+\n\x07prev_kv\x18\x03 \x01(\x0b\x32\x1a.etcd3.etcdrpc.kv.KeyValue\" \n\tEventType\x12\x07\n\x03PUT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x42\x15\n\x11io.etcd.jetcd.apiP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'etcd3.etcdrpc.kv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021io.etcd.jetcd.apiP\001'
  _globals['_KEYVALUE']._serialized_start=44
  _globals['_KEYVALUE']._serialized_end=161
  _globals['_EVENT']._serialized_start=164
  _globals['_EVENT']._serialized_end=339
  _globals['_EVENT_EVENTTYPE']._serialized_start=307
  _globals['_EVENT_EVENTTYPE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
