name: build package

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install tox
      - name: Run linters
        run: tox -e build || true

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        pyversion:
          - '3.8'
          - '3.10'
          - '3.12'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ matrix.pyversion }}
      - run: |
          pip install tox
      - name: Run unittests
        run: tox -e unittests

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install tox
      - name: Run linters
        run: tox -e lint || true

  doc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install tox
      - name: Run linters
        run: tox -e doc
